
var lines = [
    'I\'m Amit ... research enthusiastic full time Open Source Developer',
    'I have worked in India, Japan, and England',
    'I\'ve 8.5+ years industrial experience and 2 years independent opensource development experience.',
    'There are few things which are on priority for me : security, performance, response, usability, and improvement',
    'I prefer to work on Linux OS.',
    'I\'ve contributed in many opensource projects',
    'I\'m helping many developers for their first time contribution to opensource projects. Contact me if you need any support.',
    'I love writing algorithms,  Regular Expressions and SQL queries',
    'I\'ve worked on many tools and technologies. And the tool which let me focus on logic more than configuration is my preferable.',
    'I\'m less talkative but loves talking',
    'Making a giant library of books is on my wishlist... no IT related book.',
    'I want to become astronaut and I\'m completely disqualified for this job',
    'I don\'t sleep more than 7 hours (6 hours usually), hardly play any game, and hate watching TV',
    'You can scroll down to see my some of the works. All of them are opensource and free to use',
    'If you like my work, you can write a recommendation on linkedin, start my projects on Gihub, contribute to any project you want, or buy me some time.', 
    'There is much more that I didn\'t mention on this page',
    'If you\'ve an open source project idea, you may submit it on collabs for critics and advertisement. Contact me for more detail.',
    'If you want to support opensource projects you can join TEAM. Contact me for more detail.',
    'I would be happy to know more about you and to take your feedback',
    'You can sponsor any project of your choice. Tell me the medium you\'ll prefer',
    'My first Open source project was \'Grapes\'. It is flexible regular expression engine for Java' ,
];
