
var lines = [
    'Research Enthusiastic',
    'Active Open Source Developer',
    'I\'m Post Graduate in Computer Science. I thought I\'ll become scientist one day',
    'Not a big fan of Windows OS',
    'Security is on Priority',
    'Helping many developers in opensource contribution',
    'Supporting many opensource projects',
    'I have worked in India, Japan, and England',
    'I love writing algorithms,  Regular Expressions and SQL queries',
    'Prefer to work on Python, Node JS, and Java',
    'My first Open source project was \'Grapes\'. It is flexible regular expression engine for Java' ,
    '\'Grapes\' is fast and can be used on streams directly' ,
    'Do you know you can speed up network communication try Nimn data format instead of JSON.',
    'I\'m not much active on Facebook. But you can catch me on devRant.',
    'Less talkative but loves talking',
    'I want to make a big collections of books. But don\'t have the pateince to read them',
    'I want to become astronaut and find out the reason behind life. But dreams are dreams',
    'Hardly play any mobile game',
    'Hate watching TV',
    'I would be happy to know more about you',
    'My contact detail is behind the monitor',
];
